name: release

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Stable Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: release
          toolchain: stable
          components: rustfmt
          override: true

      - uses: Swatinem/rust-cache@v1

      - name: Check Formatting
        run: |
          cargo fmt --all -- --check

      - name: Build Release
        run: |
          cargo build --release

      - uses: actions/upload-artifact@v2
        with:
          name: ra-updater-x86_64-pc-windows-msvc
          path: ./target/release/ra-updater.exe

  build-mac:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2

      - name: Install Stable Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: release
          toolchain: stable
          components: rustfmt
          override: true
          
      - uses: Swatinem/rust-cache@v1

      - name: Add x86_64 target
        run: |
          rustup target add x86_64-apple-darwin

      - name: Add aarch64 target
        run: |
          rustup target add aarch64-apple-darwin

      - name: Check Formatting
        run: |
          cargo fmt --all -- --check

      - name: Build x86_64 target
        run: |
          cargo build --release --target=x86_64-apple-darwin

      - name: Build aarch64 target
        run: |
          cargo build --release --target=aarch64-apple-darwin

      - uses: actions/upload-artifact@v1
        with:
          name: ra-updater-x86_64-apple-darwin
          path: ./target/x86_64-apple-darwin/release/ra-updater
          
      - uses: actions/upload-artifact@v1
        with:
          name: ra-updater-aarch64-apple-darwin
          path: ./target/aarch64-apple-darwin/release/ra-updater
          
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update apt
        run: |
          sudo apt-get update

      - name: Install Stable Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: release
          toolchain: stable
          components: rustfmt
          override: true

      - uses: Swatinem/rust-cache@v1

      - name: Check Formatting
        run: |
          cargo fmt --all -- --check

      - name: Build Release
        run: |
          cargo build --release

      - name: Archive Linux artifact
        run: |
          tar czvf ./target/release/ra-updater.tar.gz ./target/release/ra-updater

      - uses: actions/upload-artifact@v1
        with:
          name: ra-updater-x86_64-unknown-linux-gnu
          path: ./target/release/ra-updater.tar.gz
