name: release

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      VCPKGRS_DYNAMIC: 1
    steps:
      - uses: actions/checkout@v2

      - name: Install Stable Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: Swatinem/rust-cache@v1
      
      - name: Install dependencies
        run: |
          echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
          vcpkg install openssl:x64-windows
          
      - name: Build Release
        run: |
          cargo build --release

      - uses: actions/upload-artifact@v2
        with:
          name: ra-updater-x86_64-pc-windows-msvc
          path: ./target/release/ra-updater.exe

  build-mac:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2

      - name: Install Stable Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          
      - uses: Swatinem/rust-cache@v1

      - name: Add x86_64 target
        run: |
          rustup target add x86_64-apple-darwin

      - name: Add aarch64 target
        run: |
          rustup target add aarch64-apple-darwin

      - name: Build x86_64 target
        run: |
          cargo build --release --target=x86_64-apple-darwin

      - name: Build aarch64 target
        run: |
          cargo build --release --target=aarch64-apple-darwin --features vendored
      
      - uses: actions/upload-artifact@v1
        with:
          name: ra-updater-x86_64-apple-darwin
          path: ./target/x86_64-apple-darwin/release/ra-updater
          
      - uses: actions/upload-artifact@v1
        with:
          name: ra-updater-aarch64-apple-darwin
          path: ./target/aarch64-apple-darwin/release/ra-updater
          
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update apt
        run: |
          sudo apt-get update

      - name: Install Stable Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: Swatinem/rust-cache@v1
      
      - name: Add musl target
        run: |
          rustup target add x86_64-unknown-linux-musl
      
      - name: Install dependencies
        run: |
          sudo apt-get install -y libssl-dev musl-tools

      - name: Build gnu release
        run: |
          cargo build --release --target=x86_64-unknown-linux-gnu
      
      - name: Build musl release
        run: |
          cargo build --release --target=x86_64-unknown-linux-musl --features vendored
                    
      - uses: actions/upload-artifact@v1
        with:
          name: ra-updater-x86_64-unknown-linux-gnu
          path: ./target/x86_64-unknown-linux-gnu/release/ra-updater
          
      - uses: actions/upload-artifact@v1
        with:
          name: ra-updater-x86_64-unknown-linux-musl
          path: ./target/x86_64-unknown-linux-musl/release/ra-updater
