name: release

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Stable Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: Swatinem/rust-cache@v1
      
      - name: Install dependencies
        run: |
          vcpkg install openssl:x64-windows-static
          mkdir "C:\Program Files\OpenSSL-Win64\certs"
          curl --remote-name --time-cond "C:\Program Files\OpenSSL-Win64\certs\cacert.pem" -o "C:\Program Files\OpenSSL-Win64\certs\cacert.pem" https://curl.se/ca/cacert.pem

      - name: Build Release
        run: |
          set OPENSSL_NO_VENDOR=1
          set RUSTFLAGS=-Ctarget-feature=+crt-static
          set SSL_CERT_FILE=C:\OpenSSL-Win64\certs\cacert.pem
          cargo build --release
      
      - name: Archive Windows artifact
        run: |
          tar czvf ./target/release/ra-updater-x86_64-pc-windows-msvc.tar.gz ./target/release/ra-updater.exe

      - uses: actions/upload-artifact@v2
        with:
          name: ra-updater-x86_64-pc-windows-msvc.tar.gz
          path: ./target/release/ra-updater-x86_64-pc-windows-msvc.tar.gz

  build-mac:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2

      - name: Install Stable Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          
      - uses: Swatinem/rust-cache@v1

      - name: Add x86_64 target
        run: |
          rustup target add x86_64-apple-darwin

      - name: Add aarch64 target
        run: |
          rustup target add aarch64-apple-darwin

      - name: Build x86_64 target
        run: |
          cargo build --release --target=x86_64-apple-darwin

      - name: Build aarch64 target
        run: |
          cargo build --release --target=aarch64-apple-darwin --features vendored
      
      - name: Archive macOS artifact
        run: |
          tar czvf ./target/x86_64-apple-darwin/release/ra-updater-x86_64-apple-darwin.tar.gz ./target/x86_64-apple-darwin/release/ra-updater && tar czvf ./target/aarch64-apple-darwin/release/ra-updater-aarch64-apple-darwin.tar.gz ./target/aarch64-apple-darwin/release/ra-updater 

      - uses: actions/upload-artifact@v1
        with:
          name: ra-updater-x86_64-apple-darwin.tar.gz
          path: ./target/x86_64-apple-darwin/release/ra-updater-x86_64-apple-darwin.tar.gz
          
      - uses: actions/upload-artifact@v1
        with:
          name: ra-updater-aarch64-apple-darwin.tar.gz
          path: ./target/release/aarch64-apple-darwin/ra-updater-aarch64-apple-darwin.tar.gz
          
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update apt
        run: |
          sudo apt-get update

      - name: Install Stable Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: Swatinem/rust-cache@v1
      
      - name: Add musl target
        run: |
          rustup target add x86_64-unknown-linux-musl
      
      - name: Install dependencies
        run: |
          sudo apt-get install -y libssl-dev musl-tools

      - name: Build gnu release
        run: |
          cargo build --release --target=x86_64-unknown-linux-gnu
      
      - name: Build musl release
        run: |
          cargo build --release --target=x86_64-unknown-linux-musl --features vendored

      - name: Archive Linux artifact
        run: |
          tar czvf ./target/x86_64-unknown-linux-gnu/release/ra-updater-unknown-linux-gnu.tar.gz ./target/x86_64-unknown-linux-gnu/release/ra-updater && tar czvf ./target/x86_64-unknown-linux-musl/release/ra-updater-unknown-linux-musl.tar.gz ./target/x86_64-unknown-linux-musl/release/ra-updater
                    
      - uses: actions/upload-artifact@v1
        with:
          name: ra-updater-x86_64-unknown-linux-gnu.tar.gz
          path: ./target/x86_64-unknown-linux-gnu/release/ra-updater-unknown-linux-gnu.tar.gz
          
      - uses: actions/upload-artifact@v1
        with:
          name: ra-updater-x86_64-unknown-linux-musl.tar.gz
          path: ./target/x86_64-unknown-linux-musl/release/ra-updater-unknown-linux-musl.tar.gz
